image: python:2.7-alpine

before_script:
  - apt-get install -y pelican markdown
  - pip install typogrify
  - git clone --recursive https://github.com/nasskach/pelican-blueidea.git ~/pelican-themes/blueidea
  - pelican-themes --install ~/pelican-themes/blueidea --verbose

github_pages:
  script:
    - git clone --depth 1 https://github.com/Goodup302/pelican-blog.git output
    - git config user.email "j.f0471430704@gmail.com"
    - git config --global user.name "Goodup302"
    - make clean && make html
    - cd output
    - git add -A
    - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push