image: ubuntu:18.04

before_script:
  - echo $GITHUB_ACCESS_TOKEN
  - apt-get update -y
  - apt-get upgrade -y
  - apt autoremove -y
  - apt-get install -y python-virtualenv python-dev python-pip git
  - git config user.email "j.f0471430704@gmail.com"
  - git config --global user.name "Goodup302"
  - DEBIAN_FRONTEND=noninteractive apt-get install -y pelican markdown
  - pip install typogrify
  - git clone --recursive https://github.com/nasskach/pelican-blueidea.git ~/pelican-themes/blueidea
  - pelican-themes --install ~/pelican-themes/blueidea --verbose

github_pages:
  script:
    - rm -rf output
    - git clone --depth 1 https://Goodup302:$GITHUB_ACCESS_TOKEN@github.com/Goodup302/pelican-blog.git output
    - git remote add github https://Goodup302:$GITHUB_ACCESS_TOKEN@github.com/Goodup302/pelican-blog.git
    - make clean && make html
    - cd output
    - git branch -mv github master
    - git add --all
    - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push -u github master --force
  artifacts:
    paths:
      - output